management:
    endpoint:
        health:
            show-details: "always"
    endpoints:
        web:
            base-path: '/'
            exposure:
                include:
                    - health
                    - info

base-urls:
    idam-user: ${IDAM_API_URL:http://localhost:4501}
    idam-s2s: ${S2S_URL:http://localhost:4502}
    s2s-token: ${S2S_TOKEN:AAAAAAAAAAAAAAAA}
    ccd-case-disposer-s2s-token: ${CCD_CASE_DISPOSER_S2S_TOKEN:BBBBBBBBBBBBBBBB}
    dm-store: ${TEST_URL:http://localhost:4603}
    large-docs: ${TEST_URL:https://www.dropbox.com/s}

toggle:
    metadatasearchendpoint: ${ENABLE_METADATA_SEARCH:true}
    documentandmetadatauploadendpoint: ${ENABLE_DOCUMENT_AND_METADATA_UPLOAD:true}
    folderendpoint: ${ENABLE_FOLDER_API:true}
    deleteenabled: ${ENABLE_DELETE:true}
    ttl: ${ENABLE_TTL:false}
    thumbnail: ${ENABLE_THUMBNAIL:true}
    includeidamhealth: ${ENABLE_IDAM_HEALTH_CHECK:false}
    metadatamigration: ${ENABLE_METADATA_MIGRATION:false}
    secureurl: ${ENABLE_SECURE_URL:false}
large-docs:
    metadata:
        mp4-52mb:
            id: ${MP4_52MB:84t2z2zjzhhrmt5/52MB_Video.mp4?dl=1}
            documentName: 111MB_Video
            extension: mp4
            size: 111022382

        mp4-111mb:
            id: ${MP4_111MB:vg5fj4tbm0o23z9/111MB_Video.mp4?dl=1}
            documentName: 52MB_Video
            extension: mp4
            size: 52254796

        mp4-260kb:
            id: ${MP4_260KB:test1.mp4}
            documentName: test1
            extension: mp4
            size: 26076

        mp4-465mb:
            id: ${MP4_465MB:test1.mp4}
            documentName: 465MB_Video
            extension: mp4
            size: 260760

        mp4-625mb:
            id: ${MP4_625MB:test1.mp4}
            documentName: 652MB_video_mp4
            extension: mp4
            size: 622250000

        pdf-1kb:
            id: ${PDF_1KB:1KB.pdf}
            documentName: 1KB
            extension: pdf
            size: 1000

        pdf-600mb:
            id: ${PDF_600MB:1KB.pdf}
            documentName: 600MB
            extension: pdf
            size: 1038090240

        pdf-1-2gb:
            id: ${PDF_1_2GB:1KB.pdf}
            documentName: 1.2GB
            extension: pdf
            size: 1283457024

azure:
  storage:
    connection-string: ${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING:}
    blob-container-reference: ${STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:hmctstestcontainer}
    leaseTime: ${BLOB_LEASE_TIME:15} #In seconds
