---
version: '3'

services:

    dm-store-db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=evidence
            - POSTGRES_USER=evidence
            - POSTGRES_PASSWORD=evidence
        ports:
            - 5432:5432

    azure-storage-emulator-azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - 10000:10000
        command: "azurite-blob --blobHost 0.0.0.0 --loose"
        volumes:
            - ccd-docker-azure-blob-data:/opt/azurite/folder

    service-auth-provider-app:
        image: hmctspublic.azurecr.io/rpe/service-auth-provider:latest
        environment:
            - microserviceKeys_em_gw=AAAAAAAAAAAAAAAA
            - microserviceKeys_ccd_case_disposer=AAAAAAAAAAAAAAAA
            - microserviceKeys_em_ccd_orchestrator=AAAAAAAAAAAAAAAA
            - microserviceKeys_em_stitching_api=AAAAAAAAAAAAAAAA
            - microserviceKeys_ccd_case_document_am_api=AAAAAAAAAAAAAAAA
            - microserviceKeys_ccd_gw=AAAAAAAAAAAAAAAA
            - microserviceKeys_xui_webapp=AAAAAAAAAAAAAAAA
            - microserviceKeys_ccd_data=AAAAAAAAAAAAAAAA
            - microserviceKeys_ccd_definition=AAAAAAAAAAAAAAAA
            - microserviceKeys_ccd_admin=AAAAAAAAAAAAAAAA
            - microserviceKeys_fpl_case_service=AAAAAAAAAAAAAAAA
            - microserviceKeys_am_role_assignment_service=AAAAAAAAAAAAAAAA
            - JSON_CONSOLE_PRETTY_PRINT=false
            - REFORM_SERVICE_TYPE=java
            - REFORM_SERVICE_NAME=service-auth-provider-app
            - REFORM_TEAM=rpe
            - REFORM_ENVIRONMENT=docker
            - PACKAGES_ENVIRONMENT=docker
            - PACKAGES_PROJECT=rpe
            - PACKAGES_NAME=service-auth-provider-app
            - PACKAGES_VERSION=unkown
            - TESTING_SUPPORT_ENABLED=true
        ports:
            - 4502:8489

volumes:
    pacts:
    ccd-docker-azure-blob-data:
